# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d5c5728fd9488bccc3dad45d5afd6fda387476528b6dcc06381b630e81cd96cda519dac21371c28b23c9ed2ba0ae7c45136a7570abfbe144c7974e6b8f19cd1

test:
  secret_key_base: cc18759741723183977b766e1f8c53a2a4a397ef05e41a7c10a5f4023e6ab654247a0ba54bdac50f2bffd8b9d4561e35a34f36b2ca82700bbb13e2210ace4003

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
